### ISSUE TITLE
not mapping directories

### ISSUE THREAD

**Issue by Hardcore-fs** [RyanWarwick/chia-docker-vnc-desktop#2]
you do not map the directories to mnt

just /plots

nor does their appear to be an entry for .chia or "plotting"

.chia MUST be mapped outside the container for sync dta etc.

**Comment by RyanWarwick** [comment]
@Hardcore-fs I'm assuming you did not try to run the container using the provided ```docker run``` command as specified in the README... I clearly specify volume bindings for both /plotting and .chia 

If you are referring to the Dockerfile, ENV PLOTS_DIR = /plots can actually be removed. It's not even needed. When mounting volumes in Docker, the container-side paths are automatically created.
Please make sure you understand how Docker volume mounting works before commenting, thanks.

**Comment by Hardcore-fs** [comment]
wow you are an arrogant clown
restarting the container... starts part of the reinstall again..... (and that is using docker to restart the old container)
and destroys the old keys....

even it states this:

the chia user already exists and ubuntu is installed
but nope, it runs over & regenerates a new  coin &

**Comment by Hardcore-fs** [comment]
maybe before you steal someone else code without attributing it you should check the bugs.....
#54

**Comment by RyanWarwick** [comment]
@Hardcore-fs the reason it's regenerating keys every time you restart the container, is because you didn't specify the KEYS env variable. #54 is certainly not a bug, they explicitly state to use mnemonic.txt (or any named txt file) containing your existing mnemonic keys. I also detailed ```-e KEYS``` in my readme. If you could bring up #54, did you not read their resolution as well?

I can update the README to increase awareness on specifying ```-e KEYS```, and attribute it to them, etc. But either way, it's not an issue with my Dockerfile/scripts or their implementation. It is purely your error as a user. You could have asked and clarified nicely, instead of kicking up a fuss and calling me an "arrogant clown". It is quite ironic.
